name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-and-typecheck:
    name: test-and-typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - run: npm install -g npm@11.18.0
      - run: npm ci
      - run: npm test
      - run: npm exec tsc -- --noEmit
